apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eido

resources:
- namespace.yaml
- api-deployment.yaml
- api-service.yaml
- web-deployment.yaml
- web-service.yaml
- orchestration-deployment.yaml
- redis.yaml
- network-policies.yaml
- resource-quota.yaml
- pdb.yaml

